### ISSUE TITLE
Implement fs.mkdirSync on jest-fs.js

### ISSUE THREAD

**Issue by leonardomaier** [leonardomaier/jest-fs#1]
We need to implement the mocked functionality of <code>fs.mkdirSync</code> and add a test case.

OBS: no need to implement the method options <code>{ recursive: boolean, mode: string }</code>

**Comment by tiago154** [comment]
Hi @leonardomaier , I can help with this task.

**Comment by leonardomaier** [comment]
Hi @tiago154, I just assigned you to the issue. Thank you for you help!
